### ISSUE TITLE
file name without version

### ISSUE THREAD

**Issue by dvirtz** [dairiki/hatch-zipped-directory#3]
I want to use this plugin to create a [MusicBrainz Picard](https://picard.musicbrainz.org/) plugin but it requires the zip name to be identical to the plugin name.
Can you add an option to remove the version from the file name or maybe set up a custom name?

**Comment by dairiki** [comment]
Does it work to just rename the zip file after it's been built?

**Comment by dvirtz** [comment]
Yes. Do you know of a way in hatch to automate that?

**Comment by dairiki** [comment]
> Yes. Do you know of a way in hatch to automate that?

It's admittedly a bit messy, but you can use a [custom build hook].

Put the hook code into a new file in the top-level of your project named (e.g.) `hatch_rename_zip.py`:
```py
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

class CustomBuildHook(BuildHookInterface):
    def finalize(
        self, version: str, build_data: dict[str, Any], artifact_path: str
    ) -> None:
        versioned_path = Path(artifact_path)
        stem_base, sep, stem_version = versioned_path.stem.rpartition("-")
        unversioned_path = versioned_path.with_stem(stem_base)

        self.app.display_info(
            f"hard linking {versioned_path.name} to {unversioned_path.name}"
        )
        unversioned_path.unlink(missing_ok=True)
        unversioned_path.hardlink_to(versioned_path)
```

Then, to enable the above custom hook for the `zipped-directory` target, add the following section to your `pyproject.toml`:
```toml
[tool.hatch.build.targets.zipped-directory.hooks.custom]
path = "hatch_rename_zip.py"
```

[custom build hook]: https://hatch.pypa.io/latest/plugins/build-hook/custom/

**Comment by dvirtz** [comment]
That works, thank you.
Are you reluctant to allow making the file name customizable?

**Comment by dairiki** [comment]
> Are you reluctant to allow making the file name customizable?

I'm a little hesitant to make it that easy to generate unversioned zip files. It seems like a recipe for confusion.
But if it turns out that it's a common use case, I'm amenable to adding a config option to support it.

What would the config syntax change look like?

Something as simple as adding a simple `archive-filename` option?  E.g.
```toml
[tool.hatch.build.targets.zipped-directory]
archive-filename = "my-plugin.zip"
```

That would, I think, support your case, but it's a little weird in that there is no setting for `archive-name` (other than unset) that results in the default behavior (where archive is named `{{ sanitized-project-name }}-{{ project-version }}.zip`).
(What if someone wants to retain the version in the archive name, but change the "base" (project name) part of the zip file name?)

I guess simple and more limited still might be just to add a `omit-version-from-archive-filename` boolean option.  That option, when set, would do just one thing (omit the version number from the zip file name).  (Then, in the future, should need arise, a separate option `archive-name` could be introduced to allow for overriding the use of the project name as the leading part of the zip file name.)

**Comment by dvirtz** [comment]
I'm moving away from hatch at the moment so closing this issue. Thanks for your help
